name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint
